name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
jobs:
  build-and-deploy:
    env:
      emscripten-version: 3.1.39
      boost-version: 1.81.0
      boost-version-underscore: 1_81_0
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v11
        with:
          version: $emscripten-version
          actions-cache-folder: 'emsdk-cache'
      - name: Install dependencies
        run: npm ci
      - name: Set CXX
        run: export CXX="$(which em++)"
      - name: Cache Boost library
        id: cache-boost
        uses: actions/cache@v3
        with:
          path: ${boost-version-underscore}
          key: ${boost-version-underscore}
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != true
        run: |
          wget https://boostorg.jfrog.io/artifactory/main/release/${boost-version}/source/boost_${boost-version-underscore}.tar.gz 
          && tar -xvf boost_${boost-version-underscore}.tar.gz 
          && rm boost_${boost-version-underscore}.tar.gz
          && export BOOST_ROOT=$(readlink -f boost_${boost-version-underscore})
      - name: Setup CMake
        run: npm run cmake-setup
      - name: Build
        run: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: page